import { Sora } from "next/font/google";
import type { Metadata } from "next";
import Nav from "@/app/components/nav";
import "./globals.css";
import Image from "next/image";
import Hero from "@/public/backround (r).jpg";

const inter = Sora({
  subsets: ["latin"],
  weight: "600",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        <div className="bg-[radial-gradient(ellipse_at_bottom_right,_var(--tw-gradient-stops))] from-indigo-300 via-indigo-200 to-pink-300">
          {children}
        </div>
      </body>
    </html>
  );
}
